- defaults:
    link:
        relink: true

- clean: ['~']

- shell:
    - [mkdir -p ~/bin, Creating local bin directory]
    - [mkdir -p ~/.ssh, Creating local ssh directory]

- link:
    ~/.bash_aliases: bash/aliases
    ~/.bash_logout: bash/logout
    ~/.bash_paths: bash/paths
    ~/.bash_profile: bash/profile
    ~/.bashrc: bash/bashrc
    ~/.gitconfig: git/config
    ~/.gitignore_master: git/gitignore_master
    ~/.i3: i3
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/bin/autorandr: autorandr/autorandr
    ~/.ssh/config: ssh/config

- shell:
    - [git submodule update --init --recursive, Installing submodules]
